### ISSUE TITLE
Remove reference to tab created by other module

### ISSUE THREAD

**Issue by bartoszkubicki** [WeareJH/stripped-db-provider#27]
https://github.com/WeareJH/stripped-db-provider/blob/master/src/etc/adminhtml/system.xml - Move the module to system / developer settings, where it fits properly and doesn't require another JH module

**Comment by zaxkh** [comment]
Fixed in [1.2.5.1](https://github.com/WeareJH/stripped-db-provider/releases/tag/1.2.5.1)
